- hosts: localhost
  gather_facts: false
  vars:
    vault_addr: 'http://vault.testing.ansible.com:8200'
    policy_file: "/tmp/policy.hcl"
    vault_bin: "{{ playbook_dir }}/files/vault"
  environment:
    VAULT_ADDR: '{{ vault_addr }}'
    VAULT_TOKEN: '{{ vault_token }}'
  tasks:
    - name: "Create policy file"
      template:
        src: "{{ playbook_dir }}/templates/policy.hcl.j2"
        dest: "{{ policy_file }}"

   - name: "Add policy to vault"
     shell: "{{ vault_bin }} policy-write {{ username }} {{ policy_file }}"

    - name: "Create vault user"
      shell: "{{ vault_bin }} write auth/userpass/users/{{ username }} password={{ password }} policies={{ username }}"

