- hosts: localhost
  gather_facts: false
  vars:
    vault_addr: 'http://vault.testing.ansible.com:8200'
    policy_file: "/tmp/policy.hcl"
  tasks:
    - name: "Create policy for soon to be created user"
      template:
        src: "{{ playbook_dir }}/templates/policy.hcl.j2"
        dest: "{{ policy_file }}"

    - name: "Create vault user"
      command: "{{ playbook_dir }}/files/vault write auth/userpass/users/{{ username }} password={{ password }} policies={{ policy_file }}"
      environment:
        VAULT_ADDR: '{{ vault_addr }}'
        VAULT_TOKEN: '{{ vault_token }}'

